# Generated by Django 3.2.8 on 2023-07-31 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230730_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='ref_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.CreateModel(
            name='AtivoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('timestamp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ativo')),
            ],
        ),
    ]
