# Generated by Django 3.2.8 on 2023-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230731_1819'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ativohistory',
            constraint=models.UniqueConstraint(fields=('ativo', 'timestamp'), name='unique_history'),
        ),
    ]
